name: BMS CI/CD Pipeline (Ubuntu Latest)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: bms-app
      CONTAINER_NAME: bms-app
      APP_PORT: 3000

    steps:
      # 1️⃣ Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2️⃣ Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # 3️⃣ Install dependencies
      - name: Install Dependencies
        run: |
          npm install
          chmod -R 755 node_modules/.bin

      # 4️⃣ Install Trivy & Pull ZAP Image
      - name: Install Trivy & Pull ZAP Image
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
          docker pull zaproxy/zap-stable:latest

      # 5️⃣ Trivy Filesystem Scan
      - name: Trivy FS Scan
        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL . || true

      # 6️⃣ Build React App
      - name: Build React App
        run: CI=false npm run build

      # 7️⃣ Build Docker Image
      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      # 8️⃣ Trivy Docker Image Scan
      - name: Trivy Docker Image Scan
        run: trivy image --exit-code 0 --severity HIGH,CRITICAL $IMAGE_NAME || true

      # 9️⃣ Stop & Remove Old Container
      - name: Stop & Remove Existing Container
        run: |
          if [ $(docker ps -a -q -f name=$CONTAINER_NAME) ]; then
            docker rm -f $CONTAINER_NAME
          else
            echo "No old container found"
          fi

      # 🔟 Run Docker Container
      - name: Run Docker Container
        run: |
          docker run -d -p $APP_PORT:$APP_PORT --name $CONTAINER_NAME $IMAGE_NAME
          sleep 15

      # 1️⃣1️⃣ Generate & Run Test Script
      - name: Create & Run Test Script
        run: |
          cat << 'EOF' > testscript.sh
          #!/bin/bash
          mkdir -p reports
          echo "Running basic tests..." > reports/test-report.txt

          # Check package.json
          if [ -f package.json ]; then
            echo "✅ package.json exists: Test passed" >> reports/test-report.txt
          else
            echo "❌ package.json missing: Test failed" >> reports/test-report.txt
            exit 1
          fi

          # Check build folder
          if [ -d build ]; then
            echo "✅ build folder exists: Build successful" >> reports/test-report.txt
          else
            echo "❌ build folder missing: Build failed" >> reports/test-report.txt
            exit 1
          fi

          # Check if app responds
          if curl -s http://localhost:$APP_PORT > /dev/null; then
            echo "✅ App is running and responding: Test passed" >> reports/test-report.txt
          else
            echo "❌ App not responding on port $APP_PORT: Test failed" >> reports/test-report.txt
            exit 1
          fi

          echo "All tests completed." >> reports/test-report.txt
          EOF

          chmod +x testscript.sh
          ./testscript.sh

      # 1️⃣2️⃣ Upload Test Report
      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: reports/test-report.txt
