name: BMS CI/CD Pipeline (Ubuntu Latest)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: bms-app
      CONTAINER_NAME: bms-app
      APP_PORT: 3000

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: |
          npm install
          chmod -R 755 node_modules/.bin

      - name: Install Trivy & Pull ZAP Image
        run: |
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh -s -- -b /usr/local/bin
          docker pull zaproxy/zap-stable:latest

      - name: Check Trivy Version
        run: trivy --version

      - name: Trivy FS Scan
        run: trivy fs --exit-code 0 --severity HIGH,CRITICAL . || true

      - name: Build React App
        run: CI=false npm run build

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME .

      - name: Trivy Docker Image Scan
        run: trivy image --exit-code 0 --severity HIGH,CRITICAL $IMAGE_NAME || true

      - name: Stop & Remove Existing Container
        run: |
          if [ "$(docker ps -a -q -f name=$CONTAINER_NAME)" ]; then
            docker rm -f $CONTAINER_NAME
          else
            echo "No old container found"
          fi

      - name: Run Docker Container
        run: |
          docker run -d -p $APP_PORT:$APP_PORT --name $CONTAINER_NAME $IMAGE_NAME
          sleep 15

      - name: Create Test Script
        run: |
          cat <<'EOF' > testscript.sh
#!/bin/bash
mkdir -p reports
echo "Running basic tests..." > reports/test-report.txt

if [ -f package.json ]; then
  echo "✅ package.json exists: Test passed" >> reports/test-report.txt
else
  echo "❌ package.json missing: Test failed" >> reports/test-report.txt
  exit 1
fi

if [ -d build ]; then
  echo "✅ build folder exists: Build successful" >> reports/test-report.txt
else
  echo "❌ build folder missing: Build failed" >> reports/test-report.txt
  exit 1
fi

if [ "$(docker ps -q -f name=$CONTAINER_NAME)" ]; then
  echo "✅ Docker container running: Test passed" >> reports/test-report.txt
else
  echo "❌ Docker container not running: Test failed" >> reports/test-report.txt
  exit 1
fi

echo "✅ All tests passed!" >> reports/test-report.txt
EOF
          chmod +x testscript.sh

      - name: Run Test Script
        run: ./testscript.sh

      - name: DAST Scan (OWASP ZAP)
        run: |
          docker run --rm --network host zaproxy/zap-stable zap-baseline.py \
            -t http://localhost:$APP_PORT \
            -r reports/zap-report.html || true

      - name: Upload Reports
        uses: actions/upload-artifact@v4
        with:
          name: bms-reports
          path: reports/
